=begin
#Selling Partner API for Retail Procurement Shipments

#The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

require 'date'

module AmzSpApi::VendorShipmentsApiModel
  # Shipment Information details for Label request.
  class ShipmentInformation
    attr_accessor :vendor_details

    # Buyer Reference number which is a unique number.
    attr_accessor :buyer_reference_number

    attr_accessor :ship_to_party

    attr_accessor :ship_from_party

    # Vendor Warehouse ID from where the shipment is scheduled to be picked up by buyer / Carrier.
    attr_accessor :warehouse_id

    # Unique Id with  which  the shipment can be tracked for Small Parcels.
    attr_accessor :master_tracking_id

    # Number of Labels that are created as part of this shipment.
    attr_accessor :total_label_count

    # Type of shipment whether it is Small Parcel
    attr_accessor :ship_mode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'vendor_details' => :'vendorDetails',
        :'buyer_reference_number' => :'buyerReferenceNumber',
        :'ship_to_party' => :'shipToParty',
        :'ship_from_party' => :'shipFromParty',
        :'warehouse_id' => :'warehouseId',
        :'master_tracking_id' => :'masterTrackingId',
        :'total_label_count' => :'totalLabelCount',
        :'ship_mode' => :'shipMode'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'vendor_details' => :'Object',
        :'buyer_reference_number' => :'Object',
        :'ship_to_party' => :'Object',
        :'ship_from_party' => :'Object',
        :'warehouse_id' => :'Object',
        :'master_tracking_id' => :'Object',
        :'total_label_count' => :'Object',
        :'ship_mode' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `AmzSpApi::VendorShipmentsApiModel::ShipmentInformation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `AmzSpApi::VendorShipmentsApiModel::ShipmentInformation`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'vendor_details')
        self.vendor_details = attributes[:'vendor_details']
      end

      if attributes.key?(:'buyer_reference_number')
        self.buyer_reference_number = attributes[:'buyer_reference_number']
      end

      if attributes.key?(:'ship_to_party')
        self.ship_to_party = attributes[:'ship_to_party']
      end

      if attributes.key?(:'ship_from_party')
        self.ship_from_party = attributes[:'ship_from_party']
      end

      if attributes.key?(:'warehouse_id')
        self.warehouse_id = attributes[:'warehouse_id']
      end

      if attributes.key?(:'master_tracking_id')
        self.master_tracking_id = attributes[:'master_tracking_id']
      end

      if attributes.key?(:'total_label_count')
        self.total_label_count = attributes[:'total_label_count']
      end

      if attributes.key?(:'ship_mode')
        self.ship_mode = attributes[:'ship_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      ship_mode_validator = EnumAttributeValidator.new('Object', ['SmallParcel', 'LTL'])
      return false unless ship_mode_validator.valid?(@ship_mode)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ship_mode Object to be assigned
    def ship_mode=(ship_mode)
      validator = EnumAttributeValidator.new('Object', ['SmallParcel', 'LTL'])
      unless validator.valid?(ship_mode)
        fail ArgumentError, "invalid value for \"ship_mode\", must be one of #{validator.allowable_values}."
      end
      @ship_mode = ship_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          vendor_details == o.vendor_details &&
          buyer_reference_number == o.buyer_reference_number &&
          ship_to_party == o.ship_to_party &&
          ship_from_party == o.ship_from_party &&
          warehouse_id == o.warehouse_id &&
          master_tracking_id == o.master_tracking_id &&
          total_label_count == o.total_label_count &&
          ship_mode == o.ship_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [vendor_details, buyer_reference_number, ship_to_party, ship_from_party, warehouse_id, master_tracking_id, total_label_count, ship_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        AmzSpApi::VendorShipmentsApiModel.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
