=begin
#Selling Partner API for Uploads

#The Selling Partner API for Uploads provides operations that support uploading files.

OpenAPI spec version: 2020-11-01

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

# Common files
require 'uploads-api-model/api_client'
require 'uploads-api-model/api_error'
require 'uploads-api-model/version'
require 'uploads-api-model/configuration'

# Models
require 'uploads-api-model/models/create_upload_destination_response'
require 'uploads-api-model/models/error'
require 'uploads-api-model/models/error_list'
require 'uploads-api-model/models/upload_destination'

# APIs
require 'uploads-api-model/api/uploads_api'

module AmzSpApi::UploadsApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::UploadsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
